### ISSUE TITLE
undef in `auth.rb`

### ISSUE THREAD

**Issue by yegor256** [yegor256/glogin#118]
```
NoMethodError: undefined method `[]' for nil:NilClass
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.0/lib/glogin/auth.rb:104:in `escape'
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.0/lib/glogin/auth.rb:75:in `user'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`
