### ISSUE TITLE
RuntimeError: Value 526301 is not a string

### ISSUE THREAD

**Issue by yegor256** [yegor256/glogin#122]
```
RuntimeError: Value 526301 is not a string
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.2/lib/glogin/cookie.rb:97:in `block in initialize'
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.2/lib/glogin/cookie.rb:94:in `each'
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.2/lib/glogin/cookie.rb:94:in `initialize'

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`
