### ISSUE TITLE
RuntimeError: The key node_id is not allowed

### ISSUE THREAD

**Issue by yegor256** [yegor256/glogin#123]
```
RuntimeError: The key node_id is not allowed
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.3/lib/glogin/cookie.rb:96:in `block in initialize'
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.3/lib/glogin/cookie.rb:94:in `each'
	/app/vendor/bundle/ruby/3.2.0/gems/glogin-0.16.3/lib/glogin/cookie.rb:94:in `initialize'

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.4`
