### ISSUE TITLE
undefined method `force_encoding' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/glogin#20]
```
undefined method `force_encoding' for nil:NilClass
	/app/vendor/bundle/ruby/2.6.0/gems/glogin-0.5.0/lib/glogin/codec.rb:56:in `decrypt'
	/app/vendor/bundle/ruby/2.6.0/gems/glogin-0.5.0/lib/glogin/cookie.rb:57:in `to_user'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.1`
