### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/glogin#3]
```
Failed to open TCP connection to github.com:443 (undefined method `[]' for nil:NilClass)
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	/app/vendor/bundle/ruby/2.3.0/gems/glogin-0.2.1/lib/glogin/auth.rb:80:in `access_token'
	/app/vendor/bundle/ruby/2.3.0/gems/glogin-0.2.1/lib/glogin/auth.rb:60:in `user'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.2`
