### ISSUE TITLE
fails with openssl gem

### ISSUE THREAD

**Issue by yegor256** [yegor256/glogin#5]
```
TestCookie#test_encrypts_and_decrypts:
ArgumentError: key must be 32 bytes
    /Volumes/ssd2/code/glogin/lib/glogin/cookie.rb:74:in `key='
    /Volumes/ssd2/code/glogin/lib/glogin/cookie.rb:74:in `to_s'
    /Volumes/ssd2/code/glogin/test/glogin/test_cookie.rb:36:in `test_encrypts_and_decrypts'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.4`
